### ISSUE TITLE
Check StopForumSpam reports are being submitted

### ISSUE THREAD

**Issue by philwareham** [textpattern/textpattern-forum#285]
I don't see any of our reports in our StopForumSpam control panel (although the forum does check against SFS when registering people). Need to check whether this is one of our security header rules preventing the reporting from happening or something wrong in the API.

**Comment by petecooper** [comment]
This might help - from the error log (note: IP and email address smushed):

```
PHP message: PHP Warning:  file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages:
error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed in /var/www/vhosts/textpattern.com/forum/live/lib/Textpattern/Fluxbb/Sfs.php on line 212PHP message: PHP Warning:  file_get_contents(): Failed to enable crypto in /var/www/vhosts/textpattern.com/forum/live/lib/Textpattern/Fluxbb/Sfs.php on line 212PHP message: PHP Warning:  file_get_contents(https://www.stopforumspam.com/api?f=json&amp;unix&amp;email=user%40example.com): failed to open stream: operation failed in /var/www/vhosts/textpattern.com/forum/live/lib/Textpattern/Fluxbb/Sfs.php on line 212" while reading response header from upstream, client: <IPv4 here>, server: forum.textpattern.com, request: "POST /register.php?action=register HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.3-fpm.sock:", host: "forum.textpattern.com", referrer: "https://forum.textpattern.com/register.php?agree=Agree"
```

**Comment by gocom** [comment]
@philwareham @petecooper That is due to certificate bundle PHP is using. You can provide OpenSSL up-to-date bundle, one that can validate the cert used by stopforumspam.com, from PHP's configuration file:

```
openssl.cafile=/path/to/some/bundle/cert.pem
```

Or updating the look-up locations that were set on PHP's compile time with new certs. You can get the locations OpenSSL tries to use with:

```
$ php -r 'print_r(openssl_get_cert_locations());'
```

Or you can also use any of the OpenSSL environment variables to configure OpenSSL.

As far as the bundle itself goes, you can try to use your host system's ones, or provide your own. If everything else fails easiest, but the least secure option would be to download some pre-compiled bundle.

**Comment by petecooper** [comment]
@gocom - thank you, that's really useful. PHP (currently 7.3.8) is compiled with its own OpenSSL (currently 1.1.1c), I've spotted a couple of extra trailing slashes on the compile script that might be affecting the certificates being loaded properly, I'll investigate.

**Comment by philwareham** [comment]
Sorry I already fixed the original issue here https://github.com/textpattern/fluxbb/commit/63b2770ac8d66027fb7fd88e7b03bb9aeeacf06c - just didn’t close it.

**Comment by petecooper** [comment]
The comment I left at https://github.com/textpattern/textpattern-forum/issues/285#issuecomment-524554064 related to a related issue that has now been resolved. The related issue concerned the initial SFS check that takes place when a user registers an account. PHP uses its own OpenSSL, which in turn was not loading the system CA stack, so the TLS communication could not be initialised.

After some coaxing and two dry runs, I'm using the Mozilla CA bundle with a daily cron check. PHP uses its own OpenSSL because initially the underlying OS was not running a TLS 1.3-compliant OpenSSL (1.0.something), but now it is. I'm going to continue with the current/latest OpenSSL as there are known CVEs in the system-native version.

Whether or not a single-file bundle is preferable to the system CA stack…well, I don't know at the moment. It's trivial to switch out the bundle to a symlink, so I'll monitor for now and see what transpires. Thanks again, @gocom - much appreciated.
