### ISSUE TITLE
Forum: Posting with a (proper) emoji returns error

### ISSUE THREAD

**Issue by jools-r** [textpattern/textpattern-forum#450]
**Describe the bug**
Posting a proper emoji, like a 👍 results in an 
```
An error was encountered
Error: Unable to create post.
```
Doing a preview is just fine but posting returns the error.

A post is however (partially) created but clicking on the resulting entry returns:

```
Error: The post table and topic table seem to be out of sync!
```

**To reproduce**
Steps to reproduce the behaviour:
1. Create an article and insert an emoji.
2. Click on 'Preview' and the preview will be fine.
3. Click on 'Submit' and you'll see the first error.
4. (Optional: Remove the emoji from the post and it posts successfully)
5. Visit the post list and see two entries with the same title. One of them returns the second error.

Testing on MacOS in Safari.

**Additional context**
[Forum post detailing the error and Stef's reasoning why](https://forum.textpattern.com/viewtopic.php?id=51424)

**Comment by MioVisman** [comment]
In the original FluxBB, emoji cannot be posted. Even in the preview, question marks will be displayed instead of emoji.
Why? 
1. MySQL database encoding (character collation) = utf8, not utf8mb4
2. Database connection has default client character set = utf8, not utf8mb4: https://github.com/textpattern/fluxbb/blob/e70f670a2785cb65318363ac563928dcc7cc99f5/include/dblayer/mysqli.php#L54 
3. Message input is filtered and characters longer than 3 bytes are replaced with question marks: https://github.com/textpattern/fluxbb/blob/e70f670a2785cb65318363ac563928dcc7cc99f5/post.php#L171
4. Emoji characters are 4 bytes 

P.S. Somewhere they forgot to add or subtract something once 4 byte characters go to the database, but do not fit in it ;)
P.P.S. Google Translate works very strangely :(

**Comment by philwareham** [comment]
Hope fully fixed again now, thanks everyone. Just rebuilding the post database to remove the 2 erroneous entires and it'll be back online again.

**Comment by petecooper** [comment]
>Just rebuilding the post database to remove the 2 erroneous entires and it'll be back online again.

For completeness, these needed manually removing, but they're now gone.
