### ISSUE TITLE
Check FluxBB against supported PHP 8

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern-forum#615]
At the moment, we're using FluxBB 1.5 with some modifications for newer PHP releases. Development of FluxBB has slowed in recent years, but @MioVisman has forked a currently-maintained version:

https://github.com/MioVisman/FluxBB_by_Visman

I propose we consider switching to this fork after a period of time for suitability checks. I am particularly interested in the support for current PHP (i.e. PHP 8.1) and anticipate PHP 8.2 support will be added when it's ready.

Considerations (incomplete):

- [ ] Is it a drop-in replacement (first pass checks indicate it likely is)?
- [ ] Do we need to tweak our customisations to ensure a smooth transition?
- [ ] Will it fix https://github.com/textpattern/textpattern-forum/issues/310 ?
- [ ] Is there legacy affiliation / loyalty that we need to consider should we decide to move to a fork?

FluxBB fork graph: https://github.com/fluxbb/fluxbb/network

**Comment by philwareham** [comment]
Hi Pete,

I don't have the PHP skills ti be able to do that - Jukka had customised the Flux codebase to enable Textile language and I don't know how any of that works.

It would need someone with PHP knowledge to reverse engineer or decipher what he did and patch that to the forked Flux by Visman.

The customised codebase is here: https://github.com/textpattern/fluxbb/tree/feature-textpattern-forum

Or (and this is a suggestion only) we could offer to pay @MioVisman to do it for us - there is a decent amount of money in the OpenCollective account and surely that is a viable use-case for some of the funds? Maybe they could do Textile **and** Markdown plugins?

**Comment by Bloke** [comment]
I've never looked at the codebase of the forum ever. I doubt it's rocket science, and I'm perfectly willing to review the mods and reverse ebgineer/merge changes. But if MioVisman is willing to step in and help, that'd be awesome.

**Comment by petecooper** [comment]
rev 84:

https://github.com/MioVisman/FluxBB_by_Visman/releases/tag/1.5.11.84

…has PHP 8.1 support, which I am keen to move toward since PHP 8.0 is now in security support.

**Comment by philwareham** [comment]
> ... which I am keen to move toward since PHP 8.0 is now in security support.

Unless someone can get Textile support into the by_Visman fork, then we are stuck with what we have. Textile is playing up anyway in our build, I believe (are images broken, yes?).

**Comment by MioVisman** [comment]
About textile's images.
I propose to convert links like !url! to bbcode [img] while saving a post.

Positive:
Only FluxBB parser works when displaying topic pages.

Negative:
Old posts with links like !url! need to re-save to convert to bbcode [img].

Test code:
parser.php file, preparse_bbcode() function

```
	if ($pun_config['o_make_links'] == '1')
		$text = do_clickable($text);

```
replate to

```
	if ($pun_config['o_make_links'] == '1')
		$text = do_clickable($text);

if (empty($errors)) {
	$text = preg_replace('%!(https?://[^\s\n\r]+?)!%', '[img]$1[/img]', $text);
}

```

preview:
![preview](https://user-images.githubusercontent.com/5917956/207599305-0f4cb4e9-faac-495e-9d3c-25b3ff0062d7.png)

after save:
![save](https://user-images.githubusercontent.com/5917956/207599486-331b619c-60f5-4125-bd15-f218e70c7300.png)


P.S. Instead of additional code, you need to add a hook call and implement link conversion as an addon.

**Comment by philwareham** [comment]
@petecooper I've tested our code up to PHP 8.2.4 and the software seems to work (however, I haven't checked error logs, so that might be throwing up some issues?).

I think we are stuck with our modified FluxBB code for the foreseeable future, as I don't have the time or willpower myself to move it to a different platform right now.

**Comment by petecooper** [comment]
Hey @philwareham - I'll look into PHP 8.1 as a halfway house, see if it plays nicely.
